/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// Book Sidebar
	tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
	merryBooksSidebar: [{ type: 'autogenerated', dirName: 'books/01-merry' }],
	irangBooksSidebar: [{ type: 'autogenerated', dirName: 'books/02-irang' }],
	jadeBooksSidebar: [{ type: 'autogenerated', dirName: 'books/03-jade' }],

	// Lecture Sidebar
	merryLecturesSidebar: [
		{ type: 'autogenerated', dirName: 'lectures/01-merry' },
	],
	irangLecturesSidebar: [
		{ type: 'autogenerated', dirName: 'lectures/02-irang' },
	],
	jadeLecturesSidebar: [
		{ type: 'autogenerated', dirName: 'lectures/03-jade' },
	],

	// But you can create a sidebar manually
	/*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
